"""adding new parameters to user

Revision ID: 9fc1362b8cff
Revises: f29d8c9e1f71
Create Date: 2023-04-17 11:21:33.117974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc1362b8cff'
down_revision = 'f29d8c9e1f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shippingaddress', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('CreditCard', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('CreditCard')
        batch_op.drop_column('shippingaddress')

    # ### end Alembic commands ###
