"""applying new models

Revision ID: f29d8c9e1f71
Revises: d49cd4216d4d
Create Date: 2023-04-13 16:29:44.944362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29d8c9e1f71'
down_revision = 'd49cd4216d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wine_name', sa.String(), nullable=True),
    sa.Column('winery', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('number_of_reviews', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wine_name', sa.String(), nullable=True),
    sa.Column('winery', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('number_of_reviews', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('quantity_ordered', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('time_of_order', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_wine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity_ordered', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('wine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_wine_order_id_orders')),
    sa.ForeignKeyConstraint(['wine_id'], ['wines.id'], name=op.f('fk_order_wine_wine_id_wines')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_ordered', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wine_id', sa.Integer(), nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.BLOB(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_carts_wine_id_wines'), 'wines', ['wine_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_carts_wine_id_wines'), type_='foreignkey')
        batch_op.alter_column('image',
               existing_type=sa.String(),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.drop_column('wine_id')
        batch_op.drop_column('price')
        batch_op.drop_column('quantity_ordered')

    op.drop_table('order_wine')
    op.drop_table('orders')
    op.drop_table('wines')
    # ### end Alembic commands ###
